"""SAR PDF generator using ReportLab.

Builds a professional-looking PDF document from a SAR draft with five
narrative sections: Subject Information, Activity Description, Narrative,
Reason for Suspicion, and Action Taken.
"""

import io
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from api.models.investigation import SARDraft


# ---------------------------------------------------------------------------
# Style definitions
# ---------------------------------------------------------------------------

_styles = getSampleStyleSheet()

TITLE_STYLE = ParagraphStyle(
    "SARTitle",
    parent=_styles["Title"],
    fontSize=16,
    spaceAfter=6,
    textColor=colors.HexColor("#1E293B"),
)

SUBTITLE_STYLE = ParagraphStyle(
    "SARSubtitle",
    parent=_styles["Normal"],
    fontSize=9,
    textColor=colors.HexColor("#64748B"),
    spaceAfter=14,
)

SECTION_HEADER_STYLE = ParagraphStyle(
    "SARSectionHeader",
    parent=_styles["Heading2"],
    fontSize=12,
    spaceBefore=14,
    spaceAfter=6,
    textColor=colors.HexColor("#2563EB"),
    borderPadding=(0, 0, 2, 0),
)

BODY_STYLE = ParagraphStyle(
    "SARBody",
    parent=_styles["Normal"],
    fontSize=10,
    leading=14,
    textColor=colors.HexColor("#334155"),
    spaceAfter=10,
)

FOOTER_STYLE = ParagraphStyle(
    "SARFooter",
    parent=_styles["Normal"],
    fontSize=7,
    textColor=colors.HexColor("#94A3B8"),
    alignment=1,  # center
)


# ---------------------------------------------------------------------------
# Sections
# ---------------------------------------------------------------------------

SAR_SECTIONS = [
    ("subject_info", "1. Subject Information"),
    ("activity_description", "2. Activity Description"),
    ("narrative", "3. Narrative"),
    ("reason_for_suspicion", "4. Reason for Suspicion"),
    ("action_taken", "5. Action Taken"),
]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_sar_pdf(draft: SARDraft, alert_id: str) -> bytes:
    """Generate a SAR PDF from a draft and return raw bytes.

    Args:
        draft: The SARDraft ORM model instance.
        alert_id: The alert ID for the header metadata.

    Returns:
        PDF file contents as bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    story: list = []

    # Title
    story.append(Paragraph("Suspicious Activity Report", TITLE_STYLE))

    # Metadata table
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    meta_data = [
        ["Alert ID", alert_id, "Version", str(draft.version)],
        ["Generated", generated_at, "Generated By", draft.generated_by or "AI"],
    ]
    meta_table = Table(meta_data, colWidths=[70, 180, 70, 180])
    meta_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#64748B")),
                ("TEXTCOLOR", (2, 0), (2, -1), colors.HexColor("#64748B")),
                ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#1E293B")),
                ("TEXTCOLOR", (3, 0), (3, -1), colors.HexColor("#1E293B")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(meta_table)
    story.append(Spacer(1, 10))

    # Separator line
    line_data = [[""] ]
    line_table = Table(line_data, colWidths=[doc.width])
    line_table.setStyle(
        TableStyle(
            [
                ("LINEBELOW", (0, 0), (-1, 0), 1, colors.HexColor("#E2E8F0")),
            ]
        )
    )
    story.append(line_table)
    story.append(Spacer(1, 6))

    # Sections
    for field_name, section_title in SAR_SECTIONS:
        content = getattr(draft, field_name, None) or "Not yet generated."
        story.append(Paragraph(section_title, SECTION_HEADER_STYLE))
        # Split by newlines and wrap each paragraph
        for paragraph in content.split("\n"):
            stripped = paragraph.strip()
            if stripped:
                story.append(Paragraph(stripped, BODY_STYLE))

    # Footer
    story.append(Spacer(1, 20))
    story.append(
        Paragraph(
            "Generated by AML Sentinel — Built with G.U.I.D.E.™ Framework",
            FOOTER_STYLE,
        )
    )

    doc.build(story)
    return buffer.getvalue()
