"""Add KYC and income verification fields to Customer

Revision ID: 0a43dd8ea031
Revises: cd9c7214db36
Create Date: 2026-02-26 16:05:41.566703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a43dd8ea031'
down_revision: Union[str, Sequence[str], None] = 'cd9c7214db36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kyc_verification_date', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('kyc_last_update_date', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('income_verification_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('income_verification_notes')
        batch_op.drop_column('kyc_last_update_date')
        batch_op.drop_column('kyc_verification_date')

    # ### end Alembic commands ###
